<?php

return [
   'column_data_type' => [
      1 => 'varchar',
      2 => 'char',
      3 => 'text',
      4 => 'tinytext',
      5 => 'mediumtext',
      6 => 'longtext',
      7 => 'blob',
      8 => 'tinyblob',
      9 => 'mediumblob',
      10 => 'longblob',
      11 => 'int',
      12 => 'smallint',
      13 => 'mediumint',
      14 => 'bigint',
      15 => 'tinyint',
      16 => 'float',
      17 => 'double',
      18 => 'decimal',
      19 => 'date',
      20 => 'datetime',
      21 => 'timestamp',
      22 => 'time',
      23 => 'year',
      24 => 'enum',
      25 => 'set',
      26 => 'binary',
      27 => 'varbinary',
      28 => 'geometry',
      29 => 'point',
      30 => 'linestring',
      31 => 'polygon',
      32 => 'multipoint',
      33 => 'multilinestring',
      34 => 'multipolygon',
      35 => 'geometrycollection'
   ]

   //    $column_data_type = [
   //     1 => 'Varchar',
   //     2 => 'Char',
   //     3 => 'Text',
   //     4 => 'TinyText',
   //     5 => 'MediumText',
   //     6 => 'LongText',
   //     7 => 'Blob',
   //     8 => 'TinyBlob',
   //     9 => 'MediumBlob',
   //     10 => 'LongBlob',
   //     11 => 'Int',
   //     12 => 'SmallInt',
   //     13 => 'MediumInt',
   //     14 => 'BigInt',
   //     15 => 'TinyInt',
   //     16 => 'Float',
   //     17 => 'Double',
   //     18 => 'Decimal',
   //     19 => 'Date',
   //     20 => 'Datetime',
   //     21 => 'Timestamp',
   //     22 => 'Time',
   //     23 => 'Year',
   //     24 => 'Enum',
   //     25 => 'Set',
   //     26 => 'Binary',
   //     27 => 'Varbinary',
   //     28 => 'Geometry',
   //     29 => 'Point',
   //     30 => 'LineString',
   //     31 => 'Polygon',
   //     32 => 'MultiPoint',
   //     33 => 'MultiLineString',
   //     34 => 'MultiPolygon',
   //     35 => 'GeometryCollection'
   // ];


];
